# Word2vec preprocessing

Preprocessing is not the most exciting part of NLP, but it is still one of the most important ones. Your task is to preprocess raw text (you can use your own, or [this one](http://mattmahoney.net/dc/text8.zip). For this task text preprocessing mostly consists of:

1. cleaning (mostly, if your dataset is from social media or parsed from the internet)
1. tokenization
1. building the vocabulary and choosing its size. Use only high-frequency words, change all other words to UNK or handle it in your own manner. You can use `collections.Counter` for that.
1. assigning each token a number (numericalization). In other words, make word2index и index2word objects.
1. data structuring and batching - make X and y matrices generator for word2vec (explained in more details below)

**ATTN!:** If you use your own data, please, attach a download link. 

Your goal is to make SkipGramBatcher class which returns two numpy tensors with word indices. It should be possible to use one for word2vec training. You can implement batcher for Skip-Gram or CBOW architecture, the picture below can be helpful to remember the difference.

![text](https://raw.githubusercontent.com/deepmipt/deep-nlp-seminars/651804899d05b96fc72b9474404fab330365ca09/seminar_02/pics/architecture.png)

There are several ways to do it right. Shapes could be `x_batch.shape = (batch_size, 2*window_size)`, `y_batch.shape = (batch_size,)` for CBOW or `(batch_size,)`, `(batch_size,)` for Skip-Gram. You should **not** do negative sampling here.

They should be adequately parametrized: CBOW(window_size, ...), SkipGram(window_size, ...). You should implement only one batcher in this task; and it's up to you which one to chose.

Useful links:
1. [Word2Vec Tutorial - The Skip-Gram Model](http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/)
1. [Efficient Estimation of Word Representations in Vector Space](https://arxiv.org/pdf/1301.3781.pdf)
1. [Distributed Representations of Words and Phrases and their Compositionality](http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf)

You can write the code in this notebook, or in a separate file. It can be reused for the next task. The result of your work should represent that your batch has a proper structure (right shapes) and content (words should be from one context, not some random indices). To show that, translate indices back to words and print them to show something like this:

```
text = ['first', 'used', 'against', 'early', 'working', 'class', 'radicals', 'including']

window_size = 2

# CBOW:
indices_to_words(x_batch) = \
        [['first', 'used', 'early', 'working'],
        ['used', 'against', 'working', 'class'],
        ['against', 'early', 'class', 'radicals'],
        ['early', 'working', 'radicals', 'including']]

indices_to_words(labels_batch) = ['against', 'early', 'working', 'class']

# Skip-Gram

indices_to_words(x_batch) = ['against', 'early', 'working', 'class']

indices_to_words(labels_batch) = ['used', 'working', 'early', 'radicals']]

```

If you struggle with something, ask your neighbor. If it is not obvious for you, probably someone else is looking for the answer too. And in contrast, if you see that you can help someone - do it! Good luck!

In [155]:
from part2 import process_corpus, build_vocab, CBOWBatcher

In [156]:
batcher = CBOWBatcher(batch_size=8, window_size=2, shuffle=False)

In [157]:
test_corpus = [['first', 'used', 'against', 'early', 'working', 'class', 'radicals', 'including']]

In [158]:
test_vocab = build_vocab(test_corpus, min_freq=1)

In [159]:
test_vocab

['against',
 'early',
 'class',
 'first',
 'working',
 'radicals',
 'used',
 'including']

In [160]:
batcher.init(test_corpus, test_vocab)

In [161]:
for x, y in a:
    print(x, y)

[[0 0 7 1]
 [0 4 1 2]
 [4 7 2 5]
 [7 1 5 3]
 [1 2 3 6]
 [2 5 6 8]
 [5 3 8 0]
 [3 6 0 0]] [4 7 1 2 5 3 6 8]


In [162]:
batcher.inverse_transform(x)

[['$UNK', '$UNK', 'used', 'against'],
 ['$UNK', 'first', 'against', 'early'],
 ['first', 'used', 'early', 'working'],
 ['used', 'against', 'working', 'class'],
 ['against', 'early', 'class', 'radicals'],
 ['early', 'working', 'radicals', 'including'],
 ['working', 'class', 'including', '$UNK'],
 ['class', 'radicals', '$UNK', '$UNK']]

In [163]:
batcher.inverse_transform([y])

[['first',
  'used',
  'against',
  'early',
  'working',
  'class',
  'radicals',
  'including']]